"""Debian live-build configuration tree generation."""
import os
import re
import shutil
from pathlib import Path
from typing import Any

from backend.config import get_settings
from backend.services.debian_packages import (DESKTOP_PACKAGES, ESSENTIAL_PACKAGES,
                                              expand_companions)


def sanitize_name(name: str) -> str:
    safe = re.sub(r"[^a-zA-Z0-9_-]", "-", name).strip("-")
    return (safe or "project")[:60]


def create_build_directory(project_name: str, version_number: int) -> Path:
    settings = get_settings()
    build_dir = settings.builds_dir / f"{sanitize_name(project_name)}_v{version_number}"
    build_dir.mkdir(parents=True, exist_ok=True)
    return build_dir


def generate_config_tree(config: dict[str, Any], theme: dict[str, Any] | None,
                         build_dir: Path) -> Path:
    """Write the full live-build config tree for one build."""
    from backend.services.themes import apply_theme_to_config, generate_random_theme

    config_dir = build_dir / "config"
    chroot = config_dir / "includes.chroot"
    for sub in ("package-lists", "hooks/live", "includes.chroot"):
        (config_dir / sub).mkdir(parents=True, exist_ok=True)

    _write_auto_config(config, build_dir)
    _write_package_list(config, config_dir)
    _write_setup_hook(config, config_dir)
    _write_boot_timeout_hook(config_dir)
    _write_system_includes(config, chroot)
    apply_theme_to_config(theme or generate_random_theme(), config_dir)
    _copy_templates(config_dir)
    return config_dir


def _write_auto_config(config: dict[str, Any], build_dir: Path) -> None:
    settings = get_settings()
    boot = config.get("hardware", {}).get("boot", "both")
    bootloaders = {
        "uefi": "grub-efi",
        "bios": "syslinux",
        "both": "syslinux,grub-efi",
    }.get(boot, "syslinux,grub-efi")
    hostname = sanitize_name(config.get("hostname", "custom-linux")).lower()
    username = re.sub(r"[^a-z0-9_-]", "", config.get("username", "user").lower()) or "user"

    script = f"""#!/bin/sh
set -e

lb config noauto \\
    --distribution {settings.debian_suite} \\
    --architectures amd64 \\
    --archive-areas "main contrib non-free non-free-firmware" \\
    --debian-installer none \\
    --bootappend-live "boot=live components hostname={hostname} username={username} quiet splash" \\
    --mode debian \\
    --system live \\
    --binary-images iso-hybrid \\
    --memtest none \\
    --bootloaders "{bootloaders}" \\
    --linux-packages linux-image \\
    --security true \\
    --updates true \\
    --apt-recommends false \\
    "${{@}}"
"""
    auto_dir = build_dir / "auto"
    auto_dir.mkdir(exist_ok=True)
    path = auto_dir / "config"
    path.write_text(script)
    path.chmod(0o755)


def _write_package_list(config: dict[str, Any], config_dir: Path) -> None:
    # Safety net: configs saved before a companion rule existed still get the
    # helpers their packages need at runtime (Recommends are disabled).
    expanded, _added = expand_companions(config.get("packages", []))
    user_packages = [p for p in expanded
                     if p not in ESSENTIAL_PACKAGES and p not in DESKTOP_PACKAGES]
    sections = [
        ("# Base system", ESSENTIAL_PACKAGES),
        ("# Desktop", DESKTOP_PACKAGES),
        ("# User selection", sorted(user_packages)),
    ]
    lines = []
    for header, pkgs in sections:
        lines.append(header)
        lines.extend(pkgs)
        lines.append("")
    (config_dir / "package-lists" / "main.list.chroot").write_text("\n".join(lines))


def _write_setup_hook(config: dict[str, Any], config_dir: Path) -> None:
    username = re.sub(r"[^a-z0-9_-]", "", config.get("username", "user").lower()) or "user"
    hook = f"""#!/bin/bash
# System setup hook generated by Text-to-Linux-OS
set -e

# Autologin into the Openbox session for the live user
mkdir -p /etc/lightdm
cat > /etc/lightdm/lightdm.conf <<'EOF'
[Seat:*]
autologin-user={username}
autologin-user-timeout=0
user-session=openbox
EOF

# Openbox session autostart: panel, desktop, themed wallpaper color
mkdir -p /etc/skel/.config/openbox
cat > /etc/skel/.config/openbox/autostart <<'EOF'
[ -f /etc/text-to-linux/theme.conf ] && . /etc/text-to-linux/theme.conf
command -v xsetroot >/dev/null && xsetroot -solid "${{BACKGROUND:-#101418}}" &
tint2 &
pcmanfm --desktop &
EOF
chmod +x /etc/skel/.config/openbox/autostart

echo "Text-to-Linux-OS setup complete"
"""
    path = config_dir / "hooks" / "live" / "0010-setup.hook.chroot"
    path.write_text(hook)
    path.chmod(0o755)


def _write_boot_timeout_hook(config_dir: Path) -> None:
    """live-build's default boot menus wait forever for a keypress (timeout 0),
    which stalls both the QEMU verification and unattended boots on real
    hardware. This binary-stage hook (cwd = the staged ISO tree) patches the
    syslinux/isolinux and GRUB configs to auto-boot the default entry after 5s.
    """
    hook = """#!/bin/sh
set -e
for cfg in isolinux/isolinux.cfg syslinux/syslinux.cfg; do
    if [ -f "$cfg" ]; then
        if grep -q '^timeout ' "$cfg"; then
            sed -i 's/^timeout .*/timeout 50/' "$cfg"
        else
            printf 'timeout 50\\n' >> "$cfg"
        fi
    fi
done
if [ -f boot/grub/grub.cfg ]; then
    if grep -q '^set timeout=' boot/grub/grub.cfg; then
        sed -i 's/^set timeout=.*/set timeout=5/' boot/grub/grub.cfg
    else
        printf '\\nset timeout=5\\n' >> boot/grub/grub.cfg
    fi
fi
"""
    path = config_dir / "hooks" / "live" / "9000-boot-timeout.hook.binary"
    path.write_text(hook)
    path.chmod(0o755)


def _write_system_includes(config: dict[str, Any], chroot: Path) -> None:
    hostname = sanitize_name(config.get("hostname", "custom-linux")).lower()
    etc = chroot / "etc"
    etc.mkdir(parents=True, exist_ok=True)
    (etc / "hostname").write_text(hostname + "\n")

    default_dir = etc / "default"
    default_dir.mkdir(exist_ok=True)
    (default_dir / "grub").write_text(
        f'GRUB_DEFAULT=0\nGRUB_TIMEOUT=5\nGRUB_DISTRIBUTOR="{hostname}"\n'
        'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"\nGRUB_CMDLINE_LINUX=""\n'
    )


def _copy_templates(config_dir: Path) -> None:
    """Copy any static template payloads that exist in the repo."""
    templates = get_settings().templates_dir
    mapping = {
        "plymouth-ascii": "includes.chroot/usr/share/plymouth/themes/text-to-linux",
    }
    for src_name, dest_rel in mapping.items():
        src = templates / src_name
        if src.exists():
            shutil.copytree(src, config_dir / dest_rel, dirs_exist_ok=True)


def live_build_available() -> bool:
    return shutil.which("lb") is not None
