"""Theme generation for the built ISO's desktop.

Generates harmonious palettes (HSL-derived, not pure-random RGB) and writes the
actual desktop configuration files into the live-build config tree: an Openbox
theme, tint2 panel config, LXTerminal colors, and wallpaper color.
"""
import colorsys
import random
from pathlib import Path
from typing import Any


def _hsl(h: float, s: float, l: float) -> str:
    r, g, b = colorsys.hls_to_rgb(h % 1.0, l, s)
    return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"


def generate_random_theme() -> dict[str, Any]:
    """One coherent palette: a base hue, an analogous secondary, a pop accent,
    and a dark background tinted with the base hue."""
    h = random.random()
    scheme = random.choice(["analogous", "complementary", "triadic"])
    offset = {"analogous": 0.08, "complementary": 0.5, "triadic": 0.33}[scheme]

    primary = _hsl(h, 0.62, 0.58)
    secondary = _hsl(h + offset, 0.45, 0.48)
    accent = _hsl(h + 0.5 if scheme != "complementary" else h + 0.25, 0.75, 0.62)
    background = _hsl(h, 0.28, 0.09)
    surface = _hsl(h, 0.22, 0.14)
    foreground = _hsl(h, 0.15, 0.90)

    return {
        "scheme": scheme,
        "primary": primary,
        "secondary": secondary,
        "accent": accent,
        "background": background,
        "surface": surface,
        "foreground": foreground,
        "terminal": _terminal_palette(h, primary, accent, background, foreground),
    }


def _terminal_palette(h: float, primary: str, accent: str,
                      background: str, foreground: str) -> dict[str, str]:
    return {
        "background": background,
        "foreground": foreground,
        "cursor": accent,
        "color0": _hsl(h, 0.20, 0.16), "color8": _hsl(h, 0.15, 0.35),
        "color1": "#e05561", "color9": "#ff616e",
        "color2": "#8cc265", "color10": "#a5e075",
        "color3": "#d18f52", "color11": "#f0a45d",
        "color4": primary, "color12": _hsl(h, 0.70, 0.70),
        "color5": "#c162de", "color13": "#de73ff",
        "color6": "#42b3c2", "color14": "#4cd1e0",
        "color7": _hsl(h, 0.10, 0.75), "color15": _hsl(h, 0.08, 0.92),
    }


def normalize_theme(theme: dict[str, Any]) -> dict[str, Any]:
    """Fill any missing keys (e.g. user edited only base colors)."""
    base = generate_random_theme()
    merged = {**base, **{k: v for k, v in theme.items() if v}}
    if "terminal" not in theme or not theme.get("terminal"):
        # Re-derive terminal colors from the possibly-edited base colors
        merged["terminal"] = {**base["terminal"],
                              "background": merged["background"],
                              "foreground": merged["foreground"],
                              "cursor": merged["accent"],
                              "color4": merged["primary"]}
    return merged


# ---------------------------------------------------------------- file writers

def apply_theme_to_config(theme: dict[str, Any], config_dir: Path) -> None:
    theme = normalize_theme(theme)
    chroot = Path(config_dir) / "includes.chroot"

    ob_theme_dir = chroot / "usr/share/themes/TextToLinux/openbox-3"
    ob_theme_dir.mkdir(parents=True, exist_ok=True)
    (ob_theme_dir / "themerc").write_text(_openbox_themerc(theme))

    xdg_openbox = chroot / "etc/xdg/openbox"
    xdg_openbox.mkdir(parents=True, exist_ok=True)
    (xdg_openbox / "rc.xml").write_text(_openbox_rc_xml())

    tint2_dir = chroot / "etc/xdg/tint2"
    tint2_dir.mkdir(parents=True, exist_ok=True)
    (tint2_dir / "tint2rc").write_text(_tint2rc(theme))

    lxterm_dir = chroot / "etc/skel/.config/lxterminal"
    lxterm_dir.mkdir(parents=True, exist_ok=True)
    (lxterm_dir / "lxterminal.conf").write_text(_lxterminal_conf(theme["terminal"]))

    # Wallpaper color consumed by the openbox autostart hook (hsetroot/xsetroot)
    theme_env = chroot / "etc/text-to-linux"
    theme_env.mkdir(parents=True, exist_ok=True)
    (theme_env / "theme.conf").write_text(
        "".join(f"{k.upper()}={v}\n" for k, v in theme.items()
                if isinstance(v, str) and v.startswith("#"))
    )


def _openbox_themerc(t: dict) -> str:
    return f"""# Openbox theme generated by Text-to-Linux-OS
border.width: 2
padding.width: 4
padding.height: 4
window.handle.width: 0

window.active.border.color: {t['primary']}
window.inactive.border.color: {t['surface']}

window.active.title.bg: flat solid
window.active.title.bg.color: {t['surface']}
window.active.label.text.color: {t['foreground']}
window.inactive.title.bg: flat solid
window.inactive.title.bg.color: {t['background']}
window.inactive.label.text.color: {t['secondary']}

window.active.button.unpressed.image.color: {t['foreground']}
window.active.button.hover.image.color: {t['accent']}
window.inactive.button.unpressed.image.color: {t['secondary']}

menu.title.bg: flat solid
menu.title.bg.color: {t['surface']}
menu.title.text.color: {t['accent']}
menu.items.bg: flat solid
menu.items.bg.color: {t['background']}
menu.items.text.color: {t['foreground']}
menu.items.active.bg: flat solid
menu.items.active.bg.color: {t['primary']}
menu.items.active.text.color: {t['background']}

osd.bg: flat solid
osd.bg.color: {t['surface']}
osd.label.text.color: {t['foreground']}
"""


def _openbox_rc_xml() -> str:
    return """<?xml version="1.0" encoding="UTF-8"?>
<openbox_config xmlns="http://openbox.org/3.4/rc">
  <theme>
    <name>TextToLinux</name>
    <titleLayout>NLIMC</titleLayout>
    <keepBorder>yes</keepBorder>
    <font place="ActiveWindow"><name>DejaVu Sans</name><size>10</size><weight>Bold</weight></font>
    <font place="InactiveWindow"><name>DejaVu Sans</name><size>10</size></font>
  </theme>
  <desktops><number>4</number><firstdesk>1</firstdesk></desktops>
  <keyboard>
    <keybind key="W-Return"><action name="Execute"><command>lxterminal</command></action></keybind>
    <keybind key="A-Tab"><action name="NextWindow"/></keybind>
    <keybind key="A-F4"><action name="Close"/></keybind>
  </keyboard>
</openbox_config>
"""


def _tint2rc(t: dict) -> str:
    return f"""# tint2 panel generated by Text-to-Linux-OS
# Background 1: panel
rounded = 0
border_width = 0
background_color = {t['surface']} 95
border_color = {t['surface']} 0

# Background 2: active task
rounded = 4
border_width = 0
background_color = {t['primary']} 100
border_color = {t['primary']} 100

panel_items = LTSC
panel_position = bottom center horizontal
panel_size = 100% 34
panel_padding = 8 4 8
panel_background_id = 1
panel_monitor = all

taskbar_mode = single_desktop
taskbar_padding = 4 2 4
taskbar_background_id = 0

task_text = 1
task_centered = 1
task_maximum_size = 180 30
task_padding = 8 3
task_font_color = {t['foreground']} 100
task_active_font_color = {t['background']} 100
task_background_id = 0
task_active_background_id = 2

systray_padding = 4 2 4
systray_background_id = 0

time1_format = %H:%M
time1_font = DejaVu Sans 10
clock_font_color = {t['foreground']} 100
clock_padding = 8 2
clock_background_id = 0
"""


def _lxterminal_conf(term: dict) -> str:
    palette = "\n".join(f"palette_color_{i}={term[f'color{i}']}" for i in range(16))
    return f"""[general]
fontname=Monospace 10
scrollback=2000
bgcolor={term['background']}
fgcolor={term['foreground']}
cursorblinks=true
audiblebell=false
hidemenubar=false
{palette}
color_preset=Custom
"""
